In [1]:
import pandas as pd

In [2]:
from pathlib import Path

relative_path = Path("data/processed/amazon_cellphones_clean.csv")
project_root = next(
    (path for path in (Path.cwd(), *Path.cwd().parents)
     if (path / relative_path).is_file()),
    None,
)

if project_root is None:
    raise FileNotFoundError(
        f"Could not find {relative_path} from {Path.cwd()}. "
        "Check that the file exists and that the data preprocessing step has run."
    )

df = pd.read_csv(project_root / relative_path)

C:\Users\T460P\AppData\Local\Temp\ipykernel_7964\3655589920.py:16: DtypeWarning: Columns (0: vote) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(project_root / relative_path)

In [3]:
df.head()

,asin,reviewText,summary,overall,reviewTime,unixReviewTime,verified,vote,review_date,year
0,7508492919,Looks even better in person. Be careful to not...,Can't stop won't stop looking at it,5.0,"08 4, 2014",1407110400,True,NaN,2014-08-04,2014
1,7508492919,When you don't want to spend a whole lot of ca...,1,5.0,"02 12, 2014",1392163200,True,NaN,2014-02-12,2014
2,7508492919,"so the case came on time, i love the design. I...",Its okay,3.0,"02 8, 2014",1391817600,True,NaN,2014-02-08,2014
3,7508492919,DON'T CARE FOR IT. GAVE IT AS A GIFT AND THEY...,CASE,2.0,"02 4, 2014",1391472000,True,NaN,2014-02-04,2014
4,7508492919,"I liked it because it was cute, but the studs ...",Cute!,4.0,"02 3, 2014",1391385600,True,NaN,2014-02-03,2014

In [4]:
print("Shape:", df.shape)

print("\n=== COLUMNS ===")
print(df.columns.tolist())

print("\n=== RATING ===")
print(df["overall"].value_counts().sort_index())

print("\n=== ASIN ===")
print("Unique products:", df["asin"].nunique())
print(df["asin"].value_counts().head(10))

print("\n=== YEAR ===")
print(df["year"].value_counts().sort_index())

print("\n=== SAMPLE ===")
display(df[["asin", "reviewText", "summary", "overall", "reviewTime", "review_date", "year"]].head(10))

Shape: (1127665, 10)

=== COLUMNS ===
['asin', 'reviewText', 'summary', 'overall', 'reviewTime', 'unixReviewTime', 'verified', 'vote', 'review_date', 'year']

=== RATING ===
overall
1.0     81505
2.0     57166
3.0     98213
4.0    184347
5.0    706434
Name: count, dtype: int64

=== ASIN ===
Unique products: 48186
asin
B00VH88CJ0    1682
B005NF5NTK    1634
B00X5RV14Y    1514
B00P7N0320    1513
B019PV2I3G    1508
B018JW3EOY    1506
B00G7UY3EG    1377
B00MQSMDYU    1340
B00M51DDT2    1267
B00QN1T6NM    1227
Name: count, dtype: int64

=== YEAR ===
year
2002         2
2003        16
2004        41
2005       132
2006       318
2007       679
2008      1691
2009      2405
2010      3459
2011      9147
2012     28226
2013     86859
2014    184956
2015    323067
2016    311551
2017    133170
2018     41946
Name: count, dtype: int64

=== SAMPLE ===

,asin,reviewText,summary,overall,reviewTime,review_date,year
0,7508492919,Looks even better in person. Be careful to not...,Can't stop won't stop looking at it,5.0,"08 4, 2014",2014-08-04,2014
1,7508492919,When you don't want to spend a whole lot of ca...,1,5.0,"02 12, 2014",2014-02-12,2014
2,7508492919,"so the case came on time, i love the design. I...",Its okay,3.0,"02 8, 2014",2014-02-08,2014
3,7508492919,DON'T CARE FOR IT. GAVE IT AS A GIFT AND THEY...,CASE,2.0,"02 4, 2014",2014-02-04,2014
4,7508492919,"I liked it because it was cute, but the studs ...",Cute!,4.0,"02 3, 2014",2014-02-03,2014
5,7508492919,The product looked exactly like the picture an...,Not so happy,2.0,"01 27, 2014",2014-01-27,2014
6,7508492919,I FINALLY got my case today. It took forever t...,It's cute!,3.0,"01 23, 2014",2014-01-23,2014
7,7508492919,It is a very cute case. None of the jewels hav...,Cute case,5.0,"01 17, 2014",2014-01-17,2014
8,7508492919,DO NOT BUY! this item is seriously cheap as he...,WORST ITEM!,1.0,"12 27, 2013",2013-12-27,2013
9,7508492919,I really love this case... you have to keep yo...,Pretty Cute!,4.0,"12 16, 2013",2013-12-16,2013

In [5]:
checkpoint_path = (
    project_root
    / "data"
    / "processed"
    / "explore_amazon_cellphones.pkl"
)

df.to_pickle(checkpoint_path)

print("Checkpoint saved:", checkpoint_path)
print("Shape:", df.shape)

Checkpoint saved: d:\data mining\e_waste_topic_modeling\data\processed\explore_amazon_cellphones.pkl
Shape: (1127665, 10)